interface SuperClass {

    <T> void method(T num); // T changes to Object at compile time because of type erasure


}

class SubClass implements SuperClass {

    // Bridge Method generated by compiler to preserve polymorphism
    // Overrides the super class method and redirects it to the method with Integer parameter
    public void method(Object num) {
        method((Integer) num);
    }

    // This method doesn't override super class method without the bridge method
    //  @Override annotation doesn't work for this method
    void method(Integer num) {
        System.out.println("SubClass Method");
    }
}

public class BridgeMethodTest {
    public static void main(String[] args) {
        SuperClass superClass = new SubClass();
        superClass.method(Integer.valueOf("1")); // Outputs SubClass Method
    }
}
